// Mocks generated by Mockito 5.4.6 from annotations
// in meal_planner/test/providers/recipe_upload_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:meal_planner/domain/entities/recipe.dart' as _i4;
import 'package:meal_planner/domain/repositories/recipe_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i2.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> saveRecipe(
    _i4.Recipe? recipe,
    _i5.File? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecipe,
          [
            recipe,
            image,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #saveRecipe,
            [
              recipe,
              image,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<_i4.Recipe>> getRecipesByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesByCategory,
          [category],
        ),
        returnValue: _i3.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
      ) as _i3.Future<List<_i4.Recipe>>);

  @override
  _i3.Future<List<_i4.Recipe>> getRecipesByCategories(
          List<String>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesByCategories,
          [categories],
        ),
        returnValue: _i3.Future<List<_i4.Recipe>>.value(<_i4.Recipe>[]),
      ) as _i3.Future<List<_i4.Recipe>>);

  @override
  _i3.Future<_i4.Recipe?> getRecipeById(String? recipeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipeById,
          [recipeId],
        ),
        returnValue: _i3.Future<_i4.Recipe?>.value(),
      ) as _i3.Future<_i4.Recipe?>);

  @override
  _i3.Future<void> updateRecipe(
    String? recipeId,
    _i4.Recipe? recipe,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRecipe,
          [
            recipeId,
            recipe,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecipe(String? recipeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRecipe,
          [recipeId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);
}
